# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-31 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='attributechoice',
            name='slug',
            field=models.SlugField(),
        ),
    ]
