# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-31 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0002_auto_20160331_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributechoice',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
