# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-01 05:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_product_attributes'),
        ('attribute', '0003_auto_20160331_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
            preserve_default=False,
        ),
    ]
