# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 11:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pricing', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('delivery_text', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=b'carriers')),
                ('default', models.BooleanField(default=True)),
                ('countries', models.ManyToManyField(blank=True, to='customer.Country')),
            ],
        ),
        migrations.CreateModel(
            name='CarrierPricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipping.Carrier')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.Currency')),
                ('taxrule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.Taxrule')),
            ],
        ),
    ]
