# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='countries',
            field=models.ManyToManyField(blank=True, to='customer.Country'),
        ),
    ]
