# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='product_categories', to='category.Category'),
        ),
    ]
