# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-24 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20160315_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, upload_to=b'products'),
        ),
    ]
