# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-24 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20160324_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b'products'),
        ),
    ]
