# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-01 05:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20160324_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='attributes',
        ),
    ]
