# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20160708_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdata',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
    ]
