# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 07:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20151009_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='custom_label',
            new_name='label',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='items',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='custom_url',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='item_type',
            field=models.CharField(default='category', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='menu.Menu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='object_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
