# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_code', models.CharField(max_length=3)),
                ('format', models.CharField(blank=True, max_length=10, null=True)),
                ('default', models.BooleanField(default=False)),
                ('language', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_amount', models.IntegerField(default=1)),
                ('value', models.FloatField()),
                ('value_type', models.CharField(choices=[(b'percentage', b'Percentage'), (b'value', b'Value')], max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.Currency')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Taxrule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('percentage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('value', models.IntegerField()),
                ('value_type', models.CharField(choices=[(b'percentage', b'Percentage'), (b'value', b'Value')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='pricing',
            name='taxrule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.Taxrule'),
        ),
    ]
