# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 05:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_customfield_customfieldvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_notification', to='order.Order'),
        ),
    ]
